# Generated by Django 4.1 on 2024-02-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unscramapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='sorted_word',
            field=models.CharField(db_index=True, default='', max_length=15),
        ),
    ]
