# Generated by Django 4.1 on 2024-02-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unscramapp', '0002_word_sorted_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='sorted_word',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
